# Catppuccin Mocha
set $base     #1e1e2e
set $mantle   #181825
set $crust    #11111b
set $surface0 #313244
set $text     #cdd6f4
set $subtext0 #a6adc8
set $mauve    #cba6f7
set $red      #f38ba8

# class                 border    bg        text      indicator child_border
client.focused          $mauve    $mauve    $crust    $mauve    $mauve
client.focused_inactive $surface0 $surface0 $text     $surface0 $surface0
client.unfocused        $mantle   $mantle   $subtext0 $mantle   $mantle
client.urgent           $red      $red      $base     $red      $red
